### ISSUE TITLE
API indexer ignores errors from ElasticSearch

### ISSUE THREAD

**Issue by georgiana-b** [opentrials/opentrials#646]
When I run `npm run reindex` in development, I get a log like this from the indexer:

```
npm run reindex                                                         

> opentrials-api@0.0.1 reindex /home/g/Documents/opentrials-api
> node --harmony_rest_parameters --optimize_for_size --max_old_space_size=460 --gc_interval=100 ./tools/reindex.js

2 entities being indexed in "trials_2017-01-21_1485000804873/trial" (1000 at a time).
2 successfully reindexed, 0 remaining.
Removing old indexes: trials_2017-01-21_1485000701296
```

That log is wrong because ElasticSearch actually failed to index one of the `trials` and raised the following error that was completely ignored by our indexer:

```
[2017-01-21 12:13:25,099][DEBUG][action.bulk              ] [Typhoid] [trials_2017-01-21_1485000804873][2] failed to execute bulk item (index) index {[trials_2017-01-21_1485000804873][trial][05cc77ad-5575-4c04-9309-4c64d5144b07], source[{"id":"05cc77ad-5575-4c04-9309-4c64d5144b07","source_id":"nct","identifiers":{"nct":"NCT00000774","isrctn":"ISRCTN2342342"},"public_title":"A Phase I Study to Evaluate the Safety and Immunogenicity of Recombinant HIV-1 Envelope Antigen in Children Born to HIV-Infected Mothers","brief_summary":"PRIMARY: To determine the safety of envelope recombinant proteins rgp120/HIV-1MN (Genentech) and rgp120/HIV-1SF2 (Chiron/Biocine) in infants who are of indeterminate HIV status born to HIV-infected women. To evaluate changes in viral load in infants proven to be infected and absolute CD4 counts in all immunized infants. SECONDARY: To evaluate the immunogenicity of these envelope recombinant proteins in infants of indeterminate HIV status born to HIV-infected women. Only 30-50 percent of HIV-infected infants have detectable virus at birth. Successful early sensitization to HIV envelope epitopes may help prevent infection or, alternatively, may enhance HIV-specific immune function to alter HIV replication and disease progression.","target_sample_size":2000,"gender":"both","has_published_results":true,"status":"complete","recruitment_status":"not_recruiting","registration_date":"1999-11-02T00:00:00.000Z","completion_date":"2002-02-12T00:00:00.000Z","results_exemption_date":"2001-09-14T00:00:00.000Z","locations":[{"id":"525740cd-12ef-43ba-87a0-0bf98b2c5026","name":"United States of America","type":"country","role":"recruitment_countries"},{"id":"87e4b972-1a03-4b4b-8a6e-d512f99a6c57","name":"Puerto Rico","type":"country","role":"recruitment_countries"}],"interventions":[{"id":"15b51693-b455-4851-b54c-911d958b246b","name":"rgp120/HIV-1MN","type":"drug","url":"http://localhost:10010/v1/interventions/15b51693-b455-4851-b54c-911d958b246b"},{"id":"37db8144-070a-4727-a7fe-d4c61d6c389c","name":"rgp120/HIV-1 SF-2","type":"procedure","url":"http://localhost:10010/v1/interventions/37db8144-070a-4727-a7fe-d4c61d6c389c"},{"id":"9324a829-8982-4b93-99a4-88f7af32bfac","name":"Placebo version of rgp120/HIV-1MN","type":"other","url":"http://localhost:10010/v1/interventions/9324a829-8982-4b93-99a4-88f7af32bfac"},{"id":"b7db98db-dfcd-4bb8-a8a0-8d7bf83c551b","name":"Placebo version of rgp120/HIV-1SF2","type":"other","url":"http://localhost:10010/v1/interventions/b7db98db-dfcd-4bb8-a8a0-8d7bf83c551b"}],"conditions":[{"id":"0ae7346d-09bf-4781-bde0-3c07525c462d","name":"HIV Infections","url":"http://localhost:10010/v1/conditions/0ae7346d-09bf-4781-bde0-3c07525c462d"},{"id":"e5e9a8b9-d671-48fc-8310-365f332025c3","name":"HIV Seronegativity","url":"http://localhost:10010/v1/conditions/e5e9a8b9-d671-48fc-8310-365f332025c3"}],"persons":[],"organisations":[{"id":"60a0f4b2-b0c5-4d6f-a442-4ef8e31abed5","name":"National Institute of Allergy and Infectious Diseases (NIAID)","url":"http://localhost:10010/v1/organisations/60a0f4b2-b0c5-4d6f-a442-4ef8e31abed5","role":"primary_sponsor"}],"records":[{"id":"7cd88d88-031d-11e6-b512-3e1d05defe78","source_id":"nct","is_primary":true,"last_verification_date":"2001-04-30T00:00:00.000Z","url":"http://localhost:10010/v1/trials/05cc77ad-5575-4c04-9309-4c64d5144b07/records/7cd88d88-031d-11e6-b512-3e1d05defe78","source_url":"https://clinicaltrials.gov/ct2/show/NCT00000774","updated_at":"2016-04-01T00:00:00.000Z"}],"publications":[{"id":"7cd88d88-031d-11e6-b512-3e1d05defe00","url":"http://localhost:10010/v1/publications/7cd88d88-031d-11e6-b512-3e1d05defe00","title":"Test title1","source_url":"https://clinicaltrials.gov/ct2/show/NCT00000774","source_id":"nct"},{"id":"7cd88d88-031d-11e6-b512-3e1d05defe01","url":"http://localhost:10010/v1/publications/7cd88d88-031d-11e6-b512-3e1d05defe01","title":"Test title2","source_url":"https://clinicaltrials.gov/ct2/show/NCT00000774","source_id":"nct"}],"documents":[{"id":"77b81059-19b2-4f5d-a00b-85b9c12b6002","name":"Blank Consent Form","type":"blank_consent_form","trials":[],"source_url":"http://example.com/7a80616a-9c2d-11e6-8e62-e4b3181a2c8c","url":"http://localhost:10010/v1/documents/77b81059-19b2-4f5d-a00b-85b9c12b6002","source_id":"nct"},{"id":"1d12e160-9c37-11e6-8e62-e4b3181a2c8c","name":"FDA approval document","type":"other","file":{"id":"9e536a14-75b9-11e6-8b77-86f30ca893d3","source_url":"http://example.org/file2.pdf","documentcloud_id":"2-example-file","sha1":"cb99b709a1978bd205ab9dfd4c5aaa1fc91c7523"},"trials":[],"source_url":"http://example.org/file2.pdf","fda_approval":{"id":"NDA021738-000","supplement_number":0,"type":"Approval","action_date":"2015-07-07T00:00:00.000Z","fda_application":{"id":"NDA021738","drug_name":"KETOCONAZOLE","active_ingredients":"EXTINA","url":"http://localhost:10010/v1/fda_applications/NDA021738","type":"NDA"}},"url":"http://localhost:10010/v1/documents/1d12e160-9c37-11e6-8e62-e4b3181a2c8c","source_id":"fda"}],"risks_of_bias":[{"id":"fbc67980-83af-11e6-831c-e4b3181a2c8c","source_id":"cochrane","source_url":"http://onlinelibrary.wiley.com/doi/10.1002/14651858.CD006081/full","study_id":"STD-Barr-2013","risk_of_bias_criteria":[{"id":"756b06ca-8414-11e6-a6fa-e4b3181a2c8c","name":"blinding","value":"unknown"}]}],"url":"http://localhost:10010/v1/trials/05cc77ad-5575-4c04-9309-4c64d5144b07","sources":{"nct":{"id":"nct","name":"ClinicalTrials.gov","source_url":"https://clinicaltrials.gov"},"fda":{"id":"fda","name":"U.S. Food and Drug Administration"},"cochrane":{"id":"cochrane","name":"Cochrane Library"}}}]}
MapperParsingException[failed to parse [results_exemption_date]]; nested: IllegalArgumentException[Invalid format: "2001-09-14T00:00:00.000Z" is malformed at "T00:00:00.000Z"];
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:340)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
        at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:128)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:318)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:537)
        at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:528)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1049)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

If I request all the trials after `reindex` it only shows 1 hit (the one that was successfully indexed).

I have ElasticSearch 2.3.5 running in a Docker container  and npm module `elasticsearch` version 11.0.1

Please check if this also happens in `production`. If so, please [check if all `trials` have been indexed](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-count.html).

**Comment by vitorbaptista** [comment]
Related to #545

**Comment by vitorbaptista** [comment]
Fixed on #693

**Comment by georgiana-b** [comment]
One of the requirements in opentrials/opentrials#647 is to get a `StrictDynamicMappingException` from ElasticSearch when we try to index fields that were not defined in the mapping.
While implementing that I noticed the ElasticSearch exceptions are still not propagated to the output of `npm run reindex` so I'll reopen this.
